name: Release Executables

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install pyinstaller

      - name: Build Windows exe
        shell: pwsh
        run: |
          powershell -ExecutionPolicy Bypass -File server/build.ps1 -Name nfa95

      - name: Upload Artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: nfa95-windows-x64
          path: |
            dist/nfa95.exe
            dist/.env.example

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install pyinstaller

      - name: Build Linux binary
        shell: bash
        run: |
          chmod +x server/build.sh
          ./server/build.sh nfa95

      - name: Upload Artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: nfa95-linux-x64
          path: |
            dist/nfa95
            dist/.env.example

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: nfa95-windows-x64
          path: ./artifacts/windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: nfa95-linux-x64
          path: ./artifacts/linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            artifacts/windows/nfa95.exe
            artifacts/windows/.env.example
            artifacts/linux/nfa95
            artifacts/linux/.env.example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
